name: Trabalho final Web E2E Tests


on:
  workflow_dispatch: 

jobs:
  web-tests:

    runs-on: ubuntu-latest

    steps:
    
      # clone do projeto
      - uses: actions/checkout@v4

      # conferir a versão instalada
      - name: Node version
        run: node --version

      # instalando dependências
      - name: instalando dependências
        run: npm install

      # executando os testes
      - name: Executando os testes
        run: npx cypress run
        
     # gera artefado sobre execução dos testes
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-artifacts (relatórios)         
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos
        

